production:
  adapter: mysql
  encoding: utf8
  database: tw_database
  pool: 5
  username: root
  password:
  host: localhost
  
development:
  adapter: mysql
  encoding: utf8
  database: tw_database
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: tw_test
  pool: 5
  username: root
  password:
  host: localhost


